### ISSUE TITLE
fontawesome broken when using other boost-based themes as course theme

### ISSUE THREAD

**Issue by stephanepoinsart** [willianmano/moodle-theme_moove#131]
Hello,

I'm using moove as my main moodle theme but i have to deploy other theme on the same plateform as course theme (i.e. fordson).

Whenever i'm using moove as the main theme, some fontawesome icon get broken in the course theme for some menus. If i use an other main theme (boost, clean...) and i purge all cache, it fixes the problem for my course theme.

![moove-main-and-fordson-course](https://user-images.githubusercontent.com/5949642/49658667-e285b880-fa42-11e8-960b-07d739c4188e.png)
![boost-or-clean-main-and-fordson-course](https://user-images.githubusercontent.com/5949642/49658668-e285b880-fa42-11e8-9924-eabecb1fa990.png)

Could Moove set something in some icon cache that cause this problem ?

If i change in config.php : 
`$THEME->iconsystem = '\theme_moove\util\icon_system';`
to 
`$THEME->iconsystem = \core\output\icon_system::FONTAWESOME;`
and remove ./theme/moove/classes/util/icon_system.php

This problem goes away... But i guess the file is here for a reason, so i guess it break something i don't use or i did not notice.

Best regards,

Stephane

**Comment by lazydaisy** [comment]
Hi Stephane,
Can you add a link to this issue in the Moodle Themes Forum?
I think the problem is Moove uses different Font icons than Moodle. So the conflict, if any, could be FontAwesome is overriding Moove icons but not listing them as the font code is different. And yes it is probably a Cache problem too.
One thing you could check is what order is listed in the root config.php of your site, as there is a specific method of ordering course themes.
Cheers
Mary

**Comment by willianmano** [comment]
@stephanepoinsart I use a differente font for some icons. Fontawesome is very good but some icons are too ugly.

**Comment by stephanepoinsart** [comment]
Hello. Thanks for your replies and sorry for the delay on my side.

I'm ok with any modified icons and i got it to work so you could say this is no longer an issue for me, but I created the issue just so you could know it might break something for some users.

If it's too much of an uncommon setup, you can feel free to put this issue on the back-burner until you get more reports.

Mary : i don't think i changed anything related to themes in my config.php, i changed them from the admin menus : admin -> appearance -> theme.

best regards. Stephane

**Comment by autoingresos** [comment]
Hi, @stephanepoinsart.

I have the same problem with the icons.
How did you make it work, or what did you do?

Regards.

**Comment by itsguysmiley** [comment]
This issue seems to arise when Moove is the default site theme where Course themes are allowed.  Here's our workaround...  You can read more about the issue here: https://moodle.org/mod/forum/discuss.php?d=391402.

For anyone else who has this issue, here's a workaround that seems to consistently restore other Boost-child theme's FA icons:

***for testing, set a course's default theme to Boost (you should be missing a Course Settings gear among other FA icons as this is the bug we're dealing with)

Process:
  - switch Site default theme to Boost
  - In your filesystem -> moodleInstallationDirecotry/theme rename 'moove' to '-moove'
  - load moodle.ddsb.ca/moodle/admin/index.php in a new tab and click 'upgrade Database'
  ***Icons show up again if you view the course with a default Boost theme
  - Rename '-moove' back to 'moove'
  - load moodle.ddsb.ca/moodle/admin/index.php and click 'upgrade Database'
  - Switch the site default theme back to Moove
  - Click Clear Theme Caches
  ***Presto!***

Note: Installing/Uninstalling Adaptable produces the issue consistently (likely, any Boost child theme will do this).  As is mentioned by the super helpful Gareth, this is a 'Moove' theme issue, not an Adaptable/Fordson theme problem.

**Comment by jonnyso** [comment]
I don't know if its the same issue, but I had a problem where certain icons wouldn't load on Moodle 3.9 and the only way I could get it to work was removing the theme/moove/classes/util/icon_system.php file.
