### ISSUE TITLE
Change Topic Icon?

### ISSUE THREAD

**Issue by rec16005** [willianmano/moodle-theme_moove#132]
How can I change the laptop icons to other fontawesome icons in the course Topics?
![screenshot](https://user-images.githubusercontent.com/22454226/50542662-8cf78400-0b88-11e9-972e-67e56652f0a3.jpg)

**Comment by snack753** [comment]
This might help to change the icons for the entire site:
[https://moodle.org/mod/forum/discuss.php?d=380488](https://moodle.org/mod/forum/discuss.php?d=380488)

However, I would be interested in being able to modify the icon per topic individually since my topics sometimes represent different learning phases that also require different topics. Or I might want to add Icons, that support the content in some way.

Would love to see this feature in the next version ;-)

**Comment by arryola** [comment]
Wondering if there was another fix. I've found this https://moodle.org/mod/forum/discuss.php?d=380488

`#page-course-view-topics .course-content .topics .section .card .pgr-img i.fa-laptop:before {
     content: "\f19d";
}`

but it replaces ALL the icons. is there a way to specify individual icons via id maybe?
