### ISSUE TITLE
My courses icon missing from nav bar (mobile)

### ISSUE THREAD

**Issue by janisfiss** [willianmano/moodle-theme_moove#144]
The **My courses** icon is missing from the navigation drawer/left sidebar when using the latest version of Moove (for 3.5) as the mobile theme. On both my Android phone and a user's iPhone there is no 'graduation cap' My courses icon. Checked using Chrome (on Android) and Safari (on iOS). 

Our Moodle is updated to the latest version of 3.5. 

There is no issue with the desktop version. (I don't use Moove for default tablet theme because of an issue with quizzes that I reported previously.)

**Comment by willianmano** [comment]
@janisfiss My courses were removed intentionally. We have limited space on mobile screens, so we need to prioritize things.

**Comment by nekoto-kun** [comment]
I just want to place a workaround here since one of our student asked about the same issue.

You can add a Navigation block in default Dashboard screen then Reset dashboard page for all users (if you want to apply it for all users of course). The Navigation block itself can display My Courses menu at the very first accessed page (Dashboard) after login. Use the Show/Hide blocks red arrow button on the right side of the screen to display blocks.
