### ISSUE TITLE
Feature suggestion: setting to change font

### ISSUE THREAD

**Issue by t-penguino** [willianmano/moodle-theme_moove#188]
Great theme, thank you.

I have previously been using the Essential theme which had a useful setting to easily switch font. This would be a great addition to this theme.

![Font menu](https://user-images.githubusercontent.com/54582660/70230100-86d23600-174f-11ea-93f7-bfcdfaeec269.png)

**Comment by willianmano** [comment]
Hi @t-penguino i am adding this feature in the new version. You can test it downloading the theme code from here(github). But the main purpose is to add accessible fonts.

**Comment by christianabila** [comment]
Hi @willianmano,
has this been implemented? If so, in which version? I haven't found it in 3.9.08 (2020071900).

This would be useful for Moodle installations operating in the EU, because the usage of Google Web Fonts and them being fetched from the Google Servers apparently don't comply with the EU-GDPR.

**Comment by willianmano** [comment]
@christianabila I only support the most recent Moodle version, currently 4.1. If I add this feature, it will be added in this version.
