### ISSUE TITLE
In moodle 3.8.2, the menu icons disappear when minimized.

### ISSUE THREAD

**Issue by jesusman111** [willianmano/moodle-theme_moove#200]
Hi,
In moodle 3.8.2, the menu icons disappear when minimized.
I attach images
regards

![img-1](https://user-images.githubusercontent.com/61394948/76340053-3d1f5b80-62fb-11ea-8df6-83b03fce1ebb.png)
![img-2](https://user-images.githubusercontent.com/61394948/76340068-427ca600-62fb-11ea-96f4-ddcc9f909de4.png)

**Comment by JohenVega** [comment]
The icons in version 3.8.2 disappear  too after update when minimized.

**Comment by jesusman111** [comment]
Could you make the icons not disappear?
Regards

**Comment by ga02h35x** [comment]
Same problem on moodle 3.7.5

Thank you

**Comment by ga02h35x** [comment]
Inspecting the html code, the problem is on aria-hidden. 

When bar is collapsed, the attribute aria-hidden turns to true. And this is causing the issue. 

![Captura de pantalla de 2020-03-14 21-46-06](https://user-images.githubusercontent.com/29507921/76690145-9eb63180-663d-11ea-9d26-5ed0a354154a.jpg)

![Captura de pantalla de 2020-03-14 21-46-21](https://user-images.githubusercontent.com/29507921/76690149-a4ac1280-663d-11ea-8f74-360bc310aa7a.jpg)

**Comment by ga02h35x** [comment]
To solve this issue.

Go to Site administration -> Appearance -> Themes -> Moove -> Advanced

On Raw SCSS (theme_moove|scss) insert this code:

#nav-drawer[aria-hidden=true] .list-group-item {
    display: block;
}


Now, all seems to be working

**Comment by jesusman111** [comment]
Thanks

**Comment by willianmano** [comment]
@jesusman111 thanks for reply this and @ga02h35x thanks for help the others. I just commited a new version solving it.
