### ISSUE TITLE
Hello Willian

### ISSUE THREAD

**Issue by OmarMor** [willianmano/moodle-theme_moove#205]
In Dashboard, error "Disk usage" Not calculated yet(moodledata)
![error_disk_usage](https://user-images.githubusercontent.com/63131958/78414538-df78e900-75f2-11ea-8dd6-6f2f424d20ba.png)

**Comment by willianmano** [comment]
@OmarMor This uses the cron and scheduled tasks, so, run your cron.

**Comment by OmarMor** [comment]
Excelent!!! tenks @willianmano.

**Comment by ikoral** [comment]
Hello, I have upgraded from moodle 3.8.2 to 3.8.3 and updated it to the latest stable moove. Everything works fine but disk usage doesn't seem to be ok.
I have already run cron. Cron works because I checked other outcomes such as completion. What should I do? Because of the upgrade, I changed my moodle code. But moodledata is the same.
