### ISSUE TITLE
Links in slider problem 3.8.12

### ISSUE THREAD

**Issue by t-penguino** [willianmano/moodle-theme_moove#232]
Hi,

Using Moodle 3.8. theme version 3.8.12.

When I try to add links to text in a slider this causes a break and text to be duplicated beneath. Caused by the double quote from the hyper link ends the alt attribute from the img tag.

![Slide links problem](https://user-images.githubusercontent.com/54582660/85314002-c0cb1580-b4b0-11ea-8696-8975ae7fa18d.png)

**Comment by hungi** [comment]
The problem is that unfiltered html code (without strip_tags() ) is beeing used in alt tag.

You can fix it quickly in slideshow.mustache edit this line: 

` <img class="d-block w-100 animated fadeIn" src="{{{ image }}}" alt="{{{ caption }}}">`

To this:

`<img class="d-block w-100 animated fadeIn" src="{{{ image }}}">`

**Comment by willianmano** [comment]
@t-penguino this was solved by @lukacspeter . Please update your theme.
