### ISSUE TITLE
frontpage issue

### ISSUE THREAD

**Issue by eschizo** [willianmano/moodle-theme_moove#257]
Hi there!
I'm using the 3.9 Moove version on a Moodle 3.9 with PHP 7.3.19 but it doesn't work properly. 
It doesn't show the front page login box,  displaymarketingbox and the sponsors components. There is also a problem with the customizing plugin, it's not possible to navigate through the sections and all the information is showed in one page.

Can you help me please?

**Comment by eschizo** [comment]
Hi guys!
I had been trying in other environments and the problem persists. Other themes worked very well at my Moodle.
There could be any problem with the Moove library??

**Comment by mcferdev** [comment]
I am with the same problem

**Comment by willianmano** [comment]
@mcferdev send prints, please.

**Comment by pedrojoaosa** [comment]
Hi!
I can't change the background image for my login page. After upload nothing is change. The predefined image is still displaying.
Do you help me @willianmano?

![login page image](https://user-images.githubusercontent.com/69895507/90624666-397bf300-e210-11ea-8d3a-6925f2a16fef.png)

**Comment by pedrojoaosa** [comment]
> Hi!
> I can't change the background image for my login page. After upload nothing is change. The predefined image is still displaying.
> Do you help me @willianmano?
> 
> ![login page image](https://user-images.githubusercontent.com/69895507/90624666-397bf300-e210-11ea-8d3a-6925f2a16fef.png)

Thank You. It's ok now.

**Comment by frumbert** [comment]
I updated the theme and the logon box has gone.
Moodle 3.8.2+ (Build: 20200327)
Moove 3.8.14 2020062700

The logon box should be appearing at the top here:
![image](https://user-images.githubusercontent.com/592257/97518787-0dd57000-19ec-11eb-91ba-1c06a309732a.png)

The setting is set properly - that is unticked so that it should show.
![image](https://user-images.githubusercontent.com/592257/97518952-6b69bc80-19ec-11eb-9de2-32c381eed235.png)

If I check the box, the logon drop down thingy appears on the home page. Hiding critical features is a dumb idea.
![image](https://user-images.githubusercontent.com/592257/97519016-92c08980-19ec-11eb-9a95-160ca70b7323.png)
