### ISSUE TITLE
My course is missing in nav drawer

### ISSUE THREAD

**Issue by Jillina** [willianmano/moodle-theme_moove#296]
Hi, I am really new to Moodle and Moove. I am trying to give course access to guests and I realised "My Course" is missing in the nav drawer and I am not able to give course access to all guests. I am using Desktop. So I am not sure if I changed some sort of setting accidentally to make it disappear. Please help. Thanks a lot!

Also by the way, I am wondering if I am able to remove some items from nav drawers as I don't really need them and they can be confusing for students. Thanks again!

![Screen Shot 2021-02-17 at 7 30 30 pm](https://user-images.githubusercontent.com/79191535/108176948-b6077400-7156-11eb-8186-cbfa0617eddb.png)

**Comment by nekoto-kun** [comment]
"My course" menu will only shown if a user (who has been created) actually enrolled to one or more courses available, cmiiw. Guest on the other side won't need that since they only able to view without participating. You may want to learn about Guest access from the [official documentation](https://docs.moodle.org/310/en/Guest_access).
