### ISSUE TITLE
Child Theme Support

### ISSUE THREAD

**Issue by Myddna** [willianmano/moodle-theme_moove#318]
Hi!

I need to do some changes to the theme and started to make a child theme following moodle's documentation.

However, I found out that the settings configured in the child theme are ignored.

Is this working as intended? Is there any way to make a functional child theme based on Moove?

Thank you!
Marta.

**Comment by msr930** [comment]
Hi Marta, please check out the link below:
https://docs.moodle.org/dev/Creating_a_theme_based_on_boost

**Comment by Myddna** [comment]
@msr930 Hi! That's exactly what we did and it didn't work.

**Comment by msr930** [comment]
Check out the link below for a child theme that works:
https://github.com/h5p/h5pmods-moodle-plugin
In order to override styles, the only function you need in renderers.php is the one that alters styles. you can delete other functions. You should also edit the theme name and versions in config.php, version.php and the php file in /lang/en
and define the parents.
After cloning the directory when you login to the moodle directory as admin, you'll be prompted to follow some steps to install the theme. After changing the current them and clearing caches it should work.
