### ISSUE TITLE
Images slides no responsive? 

### ISSUE THREAD

**Issue by laonse** [willianmano/moodle-theme_moove#377]
Hello willianmano, I manage two platforms with Moove theme. One with Moodle 3.11 and another in which I am testing with Moodle 4.0.1. In the latter, the slide images of the main page are not fully visible as in version 3.11 when using a smartphone.
Another aspect that I think is getting worse is the image of the course in the header that is no longer there, can I do something to put it back like before?
Thank you very much for your work and attention. Cheers

![Screenshot_2022-07-11-16-45-54-121_com android chrome](https://user-images.githubusercontent.com/109090154/178294416-6450d5cf-433d-42f9-80c1-38ec328559d5.jpg)

**Screenshots**

**Comment by willianmano** [comment]
@laonse about the header image: this image is a good feature but with a bad implementation. Moodle only offers one field to add course images and this same image is used in a lot of areas. Most part of users had problems with this, because almost always, the image is good for the course header and bad for the course card box. This is why I removed it.
