### ISSUE TITLE
Presets Not Loading

### ISSUE THREAD

**Issue by b-visible** [willianmano/moodle-theme_moove#41]
I've been working with the Presets feature of the Moove theme for the Moodle 3.4 version. When I load different presets that I've created or from the repository found at https://moodle.net/mod/data/view.php?id=28 do have any effect on the site. I am wondering if there is a bug or issue with the Presets feature?

**Comment by JavadocMD** [comment]
I think I'm running into this with Moove 3.8.12 and Moodle 3.8.3. No matter what I do I can't seem to get a preset file to take effect. (I even used the Moodle Sandbox site to verify that I was doing right steps.)

**Comment by JavadocMD** [comment]
I got this to work and I think I know why. I added my preset file to _both_ the Moove and the Boost file areas (`theme_moove | presetfiles` and `theme_boost | presetfiles`). Then I selected my custom preset in Boost's settings (`theme_boost | preset`). Then it worked.

I got the idea to try this from reading Moove's lib.php: `function theme_moove_get_main_scss_content($theme)` appears to use Boost's settings but then -- if your selected preset is not `default.scss` or `plain.scss` -- attempts to load the file from _Moove's_ file area. This feels like it was not intentional. (At least, assuming I'm reading this code right. I'm new to Moodle theming.)
