### ISSUE TITLE
where is the navbar in the course page?

### ISSUE THREAD

**Issue by sabersaberi2** [willianmano/moodle-theme_moove#453]
**Describe the bug**
i can't find navigation in the course page
**To Reproduce**
go to any course first page

**Expected behavior**
show something such as:
home/categoryA/courseB

**Your environment (please complete the following information):**
 - Moodle version: 4.2.1
 - Moove version 
4.2.1
2023051000

 - Browser chrome 

**Additional context**
you can see navbar in the activity of the course :
courseB/activity C
but i want see 
home/cat A/course B in the first page of course. in the default classic theme you can see navbar such as i say but in the moove we can not see that.

**Comment by brankopetric** [comment]
Ok, we had the same issue. It is easier to jump back to category from breadcrumbs, sometimes :)

This is not a bug, since this navigation is generated by parent theme Boost.

If you want to have categories in breadcrumbs. This is how I add quick fix for it:
1. Copy file: .../theme/boost/classes/boostnavbar.php to .../theme/moove/classes/
2. Edit  .../theme/moove/classes/boostnavbar.php and replace next line.
`namespace theme_boost; with namespace theme_moove;`

3. In same file comment some lines:
line 79:` //$this->remove($item->key, \breadcrumb_navigation_node::TYPE_CATEGORY);`
line 83: `//$this->remove($this->page->course->id, \breadcrumb_navigation_node::TYPE_COURSE);` 
line 114: `//$this->remove($item->key, \breadcrumb_navigation_node::TYPE_CATEGORY);`

4. If you are admin redirect your browser to Notifications page  .../admin/index.php . This will ask moodle to find this new class, autoload.

5. Edit file .../theme/moove/classes/output/core_renderer.php  and at the bootom of the file before last } add this lines. This will override boost function navbar();

`/**
     * Renders the "breadcrumb" for all pages in boost.
     *
     * @return string the HTML for the navbar.
     */
    public function navbar(): string {
        $newnav = new \theme_moove\boostnavbar($this->page);
        return $this->render_from_template('core/navbar', $newnav);
    }

6. Purge theme cache

But I believe adding setting option to a theme to choose boost like navigation or classic navigation(with categories)  will be much better option and it wont be hard to add it in code.
Maybe also some additional CSS for breadcrumbs can be added since it may become too long in some cases.

Hope this helps!

**Comment by willianmano** [comment]
@sabersaberi2 @christopherm00 thank you for reply this. @brankopetric thank you for contributing to it. I created a new option to choose between boost and classic breadcrumb.

**Comment by brankopetric** [comment]
Thank you for the fast response :D
