### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by robbl71** [willianmano/moodle-theme_moove#48]
I like very much you theme and I am sure will be much better in the next future. For now I  would like to to custom font size. Is that possible now? Thanks for you work.

**Comment by Frossard** [comment]
Hi,
There's a way to make easily this adjustment without customize CSS file of the theme. Follow the below link to download a accessibility plugin:

https://moodle.org/plugins/block_accessibility

Otherwise if you have a knowledge about CSS, follow the path:

[your_moodle_folder]/themes/moove/scss/moove.scss 

and change font-size.

**Comment by willianmano** [comment]
Its complicated to create a configuration for font size, but you can do it changing the source code.

Edit the file [your_moodle_folder]/themes/moove/scss/moove/_variables.scss and add the follow variables and change the values as you wish.

$font-size-root: 16px !default;

$font-size-base: 1rem !default;
$font-size-lg:   1.25rem !default;
$font-size-sm:   .875rem !default;
$font-size-xs:   .75rem !default;

$font-size-h1: 2.5rem !default;
$font-size-h2: 2rem !default;
$font-size-h3: 1.75rem !default;
$font-size-h4: 1.5rem !default;
$font-size-h5: 1.25rem !default;
$font-size-h6: 1rem !default;
