### ISSUE TITLE
Override activity icons

### ISSUE THREAD

**Issue by Razzo1987** [willianmano/moodle-theme_moove#49]
How can I change the icon about the activity/resources?
(ex: pdf, archive, url, ...)

**Comment by Razzo1987** [comment]
I understand that I can put some images here:
moove/pix_plugins/mod/XXX/icon.svg, where XXX can be "forum", "page", "quiz", "url", ...
but I didn't understan how can I change PDF icon

**Comment by Frossard** [comment]
I think this is actually a Moodle issue, not theme. But you can found icons about resources activity module on the below path:

`[moodle_instance]/pix/f/`

Take a look.

**Comment by willianmano** [comment]
Hi @Frossard  you're almost right. The folder for core images is **pix_core** instead of **pix**.

@Razzo1987  to do it you need to create a new folder `[moodle_instance]/theme/moove/pix_core/f/` and add the images related to the pdf following the original images.

You can see the original images in the folder` [moodle_instance]/pix/f`
