### ISSUE TITLE
align box ?

### ISSUE THREAD

**Issue by jmd87fr** [willianmano/moodle-theme_moove#76]
Hi William,
very good  the new release :-) ! 
Do you have some tips to have a good alignement of courses in the front page ( picture size  + texte )
![setting](https://user-images.githubusercontent.com/5038301/38276086-358fc916-3794-11e8-89e0-452d925f3c1d.jpg)

Do you have a table with the right size of each picture used in Moove ?

May be change the 'Dasboard' icone in the left menu because it is the same as 'Home'  (house) ??
@+

**Comment by willianmano** [comment]
I can't fix this height forcing a pre-defined value, everyone uses it with its custom content. The advice is to use images with the same height and short course descriptions within the same size.

About the dashboard icon, its a Moodle limitation when you set the frontpage as the main page instead of the panel page.
